// Code generated by go-swagger; DO NOT EDIT.

package verysimple

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddVerysimpleCreatedCode is the HTTP code returned for type AddVerysimpleCreated
const AddVerysimpleCreatedCode int = 201

/*AddVerysimpleCreated Record created

swagger:response addVerysimpleCreated
*/
type AddVerysimpleCreated struct {
}

// NewAddVerysimpleCreated creates AddVerysimpleCreated with default headers values
func NewAddVerysimpleCreated() *AddVerysimpleCreated {

	return &AddVerysimpleCreated{}
}

// WriteResponse to the client
func (o *AddVerysimpleCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// AddVerysimpleMethodNotAllowedCode is the HTTP code returned for type AddVerysimpleMethodNotAllowed
const AddVerysimpleMethodNotAllowedCode int = 405

/*AddVerysimpleMethodNotAllowed Invalid input

swagger:response addVerysimpleMethodNotAllowed
*/
type AddVerysimpleMethodNotAllowed struct {
}

// NewAddVerysimpleMethodNotAllowed creates AddVerysimpleMethodNotAllowed with default headers values
func NewAddVerysimpleMethodNotAllowed() *AddVerysimpleMethodNotAllowed {

	return &AddVerysimpleMethodNotAllowed{}
}

// WriteResponse to the client
func (o *AddVerysimpleMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}
