// Code generated by go-swagger; DO NOT EDIT.

package verysimple

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/stevef1uk/test4/models"
)

// NewAddVerysimpleParams creates a new AddVerysimpleParams object
// no default values defined in spec.
func NewAddVerysimpleParams() AddVerysimpleParams {

	return AddVerysimpleParams{}
}

// AddVerysimpleParams contains all the bound params for the add verysimple operation
// typically these are obtained from a http.Request
//
// swagger:parameters addVerysimple
type AddVerysimpleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The fields of the table that needs to be populates in JSON form
	  Required: true
	  In: body
	*/
	Body *models.Verysimple
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddVerysimpleParams() beforehand.
func (o *AddVerysimpleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Verysimple
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body", ""))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
