version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test4"
s3_bucket = "com.sjfisher.lam"
s3_prefix = "test4"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

