// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Simple API
//
//  A generated file representing a Cassandra Table definition
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
