// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A generated file representing a Cassandra Table definition",
    "title": "Simple API",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/verysimple": {
      "get": {
        "description": "Returns rows from the Cassandra table",
        "summary": "Retrieve some records from the Cassandra table",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "Primary Key field in Table",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of records",
            "schema": {
              "type": "array",
              "items": {
                "required": [
                  "id",
                  "message"
                ],
                "properties": {
                  "id": {
                    "type": "integer"
                  },
                  "message": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Record not found"
          },
          "default": {
            "description": "Sorry unexpected error"
          }
        }
      },
      "post": {
        "description": "Adds or updates a row in the Cassandra table",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Verysimple"
        ],
        "summary": "Add a new record to the Cassandra table",
        "operationId": "addVerysimple",
        "parameters": [
          {
            "description": "The fields of the table that needs to be populates in JSON form",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Verysimple"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Record created"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  },
  "definitions": {
    "Verysimple": {
      "properties": {
        "id": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "A generated file representing a Cassandra Table definition",
    "title": "Simple API",
    "version": "1.0.0"
  },
  "host": "localhost",
  "basePath": "/v1",
  "paths": {
    "/verysimple": {
      "get": {
        "description": "Returns rows from the Cassandra table",
        "summary": "Retrieve some records from the Cassandra table",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "description": "Primary Key field in Table",
            "name": "id",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A list of records",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/GetVerysimpleOKBodyItems0"
              }
            }
          },
          "400": {
            "description": "Record not found"
          },
          "default": {
            "description": "Sorry unexpected error"
          }
        }
      },
      "post": {
        "description": "Adds or updates a row in the Cassandra table",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Verysimple"
        ],
        "summary": "Add a new record to the Cassandra table",
        "operationId": "addVerysimple",
        "parameters": [
          {
            "description": "The fields of the table that needs to be populates in JSON form",
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Verysimple"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Record created"
          },
          "405": {
            "description": "Invalid input"
          }
        }
      }
    }
  },
  "definitions": {
    "GetVerysimpleOKBodyItems0": {
      "required": [
        "id",
        "message"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Verysimple": {
      "properties": {
        "id": {
          "type": "integer"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
