// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetVerysimpleOKCode is the HTTP code returned for type GetVerysimpleOK
const GetVerysimpleOKCode int = 200

/*GetVerysimpleOK A list of records

swagger:response getVerysimpleOK
*/
type GetVerysimpleOK struct {

	/*
	  In: Body
	*/
	Payload []*GetVerysimpleOKBodyItems0 `json:"body,omitempty"`
}

// NewGetVerysimpleOK creates GetVerysimpleOK with default headers values
func NewGetVerysimpleOK() *GetVerysimpleOK {

	return &GetVerysimpleOK{}
}

// WithPayload adds the payload to the get verysimple o k response
func (o *GetVerysimpleOK) WithPayload(payload []*GetVerysimpleOKBodyItems0) *GetVerysimpleOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get verysimple o k response
func (o *GetVerysimpleOK) SetPayload(payload []*GetVerysimpleOKBodyItems0) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVerysimpleOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*GetVerysimpleOKBodyItems0, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetVerysimpleBadRequestCode is the HTTP code returned for type GetVerysimpleBadRequest
const GetVerysimpleBadRequestCode int = 400

/*GetVerysimpleBadRequest Record not found

swagger:response getVerysimpleBadRequest
*/
type GetVerysimpleBadRequest struct {
}

// NewGetVerysimpleBadRequest creates GetVerysimpleBadRequest with default headers values
func NewGetVerysimpleBadRequest() *GetVerysimpleBadRequest {

	return &GetVerysimpleBadRequest{}
}

// WriteResponse to the client
func (o *GetVerysimpleBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

/*GetVerysimpleDefault Sorry unexpected error

swagger:response getVerysimpleDefault
*/
type GetVerysimpleDefault struct {
	_statusCode int
}

// NewGetVerysimpleDefault creates GetVerysimpleDefault with default headers values
func NewGetVerysimpleDefault(code int) *GetVerysimpleDefault {
	if code <= 0 {
		code = 500
	}

	return &GetVerysimpleDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get verysimple default response
func (o *GetVerysimpleDefault) WithStatusCode(code int) *GetVerysimpleDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get verysimple default response
func (o *GetVerysimpleDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *GetVerysimpleDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
